spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url:  jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useSSL=false
  session:
    store-type: none
  http:
    encoding:
      charset: utf-8
mybatis:
  type-aliases-package: com.test.springboot.mapper
  mapper-locations: classpath*:mapper/*Mapper.xml
server:
  port: 8082


#server:
#  servlet:
#    context-path: /demo
#    port:8088